#!/bin/sh

pkg=libcereal-dev
if [ "$ADTTMP" = "" ] ; then
  ADTTMP=`mktemp -d /tmp/${pkg}-test.XXXXXX`
fi
cd $ADTTMP


cp -rs /usr/share/doc/libcereal-dev/tests/* .
for file in `find . -name "*.gz"`; do gunzip < ${file} > ${file%%.gz}; done
cmake -DONLY_TEST=on -DSKIP_PORTABILITY_TEST=on .
make
